// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	verifycode "im-zero/app/verifycode/cmd/api/internal/handler/verifycode"
	"im-zero/app/verifycode/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// send verifycode
				Method:  http.MethodPost,
				Path:    "/verifycode/send",
				Handler: verifycode.SendSmsCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/verifycode/v1"),
	)
}
