// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: verifycode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送验证码请求
type SendSmsCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` // 手机号
	Scene  int32  `protobuf:"varint,2,opt,name=scene,proto3" json:"scene,omitempty"`  // 场景: 1-注册 2-登录 3-重置密码
}

func (x *SendSmsCodeReq) Reset() {
	*x = SendSmsCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifycode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeReq) ProtoMessage() {}

func (x *SendSmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_verifycode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeReq.ProtoReflect.Descriptor instead.
func (*SendSmsCodeReq) Descriptor() ([]byte, []int) {
	return file_verifycode_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsCodeReq) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

type SendSmsCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodeKey string `protobuf:"bytes,1,opt,name=codeKey,proto3" json:"codeKey,omitempty"` // 验证码key（用于后续验证）
}

func (x *SendSmsCodeResp) Reset() {
	*x = SendSmsCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifycode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSmsCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeResp) ProtoMessage() {}

func (x *SendSmsCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_verifycode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeResp.ProtoReflect.Descriptor instead.
func (*SendSmsCodeResp) Descriptor() ([]byte, []int) {
	return file_verifycode_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsCodeResp) GetCodeKey() string {
	if x != nil {
		return x.CodeKey
	}
	return ""
}

// 验证验证码请求
type VerifySmsCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile  string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`   // 手机号
	Code    string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`       // 验证码
	CodeKey string `protobuf:"bytes,3,opt,name=codeKey,proto3" json:"codeKey,omitempty"` // 验证码key
	Scene   int32  `protobuf:"varint,4,opt,name=scene,proto3" json:"scene,omitempty"`    // 场景
}

func (x *VerifySmsCodeReq) Reset() {
	*x = VerifySmsCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifycode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsCodeReq) ProtoMessage() {}

func (x *VerifySmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_verifycode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsCodeReq.ProtoReflect.Descriptor instead.
func (*VerifySmsCodeReq) Descriptor() ([]byte, []int) {
	return file_verifycode_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySmsCodeReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *VerifySmsCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifySmsCodeReq) GetCodeKey() string {
	if x != nil {
		return x.CodeKey
	}
	return ""
}

func (x *VerifySmsCodeReq) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

type VerifySmsCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
}

func (x *VerifySmsCodeResp) Reset() {
	*x = VerifySmsCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verifycode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySmsCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySmsCodeResp) ProtoMessage() {}

func (x *VerifySmsCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_verifycode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySmsCodeResp.ProtoReflect.Descriptor instead.
func (*VerifySmsCodeResp) Descriptor() ([]byte, []int) {
	return file_verifycode_proto_rawDescGZIP(), []int{3}
}

func (x *VerifySmsCodeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_verifycode_proto protoreflect.FileDescriptor

var file_verifycode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3e, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x64,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x64, 0x65,
	0x4b, 0x65, 0x79, 0x22, 0x6e, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0x82, 0x01, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x36, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x6d, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_verifycode_proto_rawDescOnce sync.Once
	file_verifycode_proto_rawDescData = file_verifycode_proto_rawDesc
)

func file_verifycode_proto_rawDescGZIP() []byte {
	file_verifycode_proto_rawDescOnce.Do(func() {
		file_verifycode_proto_rawDescData = protoimpl.X.CompressGZIP(file_verifycode_proto_rawDescData)
	})
	return file_verifycode_proto_rawDescData
}

var file_verifycode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_verifycode_proto_goTypes = []any{
	(*SendSmsCodeReq)(nil),    // 0: pb.SendSmsCodeReq
	(*SendSmsCodeResp)(nil),   // 1: pb.SendSmsCodeResp
	(*VerifySmsCodeReq)(nil),  // 2: pb.VerifySmsCodeReq
	(*VerifySmsCodeResp)(nil), // 3: pb.VerifySmsCodeResp
}
var file_verifycode_proto_depIdxs = []int32{
	0, // 0: pb.Verifycode.SendSmsCode:input_type -> pb.SendSmsCodeReq
	2, // 1: pb.Verifycode.VerifySmsCode:input_type -> pb.VerifySmsCodeReq
	1, // 2: pb.Verifycode.SendSmsCode:output_type -> pb.SendSmsCodeResp
	3, // 3: pb.Verifycode.VerifySmsCode:output_type -> pb.VerifySmsCodeResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_verifycode_proto_init() }
func file_verifycode_proto_init() {
	if File_verifycode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_verifycode_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SendSmsCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifycode_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SendSmsCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifycode_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VerifySmsCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verifycode_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*VerifySmsCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_verifycode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verifycode_proto_goTypes,
		DependencyIndexes: file_verifycode_proto_depIdxs,
		MessageInfos:      file_verifycode_proto_msgTypes,
	}.Build()
	File_verifycode_proto = out.File
	file_verifycode_proto_rawDesc = nil
	file_verifycode_proto_goTypes = nil
	file_verifycode_proto_depIdxs = nil
}
