version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: PXDN93VRKUm8TeE7
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./deploy/sql:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    restart: always
    networks:
      - imzero_net

  # Redis 缓存服务
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass G62m50oigInC30sf --appendonly yes"
    privileged: true
    restart: always
    networks:
      - imzero_net

  # Etcd 服务注册中心
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./data/etcd:/bitnami/etcd
    networks:
      - imzero_net

  # MongoDB 数据库 (用于消息存储)
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./data/mongo:/data/db
    networks:
      - imzero_net

  # MongoDB Web 管理界面
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_BASICAUTH_USERNAME=webadmin
      - ME_CONFIG_BASICAUTH_PASSWORD=webpassword
    depends_on:
      - mongo
    networks:
      - imzero_net

  # Prometheus 监控
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./deploy/prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - "9090:9090"
    networks:
      - imzero_net

  # Filebeat 日志收集 (可选)
  filebeat:
    image: elastic/filebeat:8.12.2
    container_name: im-filebeat
    environment:
      - TZ=Asia/Shanghai
    user: root
    restart: always
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./deploy/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - imzero_net
    depends_on:
      - redis

  # MinIO 对象存储服务
  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"     # API端口
      - "9001:9001"     # Console端口
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - imzero_net

  # MinIO Client (用于初始化bucket)
  minio-init:
    image: minio/mc:RELEASE.2024-05-28T14-59-31Z
    container_name: minio-init
    depends_on:
      - minio
    environment:
      TZ: Asia/Shanghai
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/im-files --ignore-existing;
      /usr/bin/mc mb myminio/im-avatars --ignore-existing;
      /usr/bin/mc mb myminio/im-temp --ignore-existing;
      /usr/bin/mc anonymous set public myminio/im-avatars;
      /usr/bin/mc anonymous set download myminio/im-temp;
      echo 'MinIO buckets initialized successfully';
      echo 'Buckets created: im-files (private), im-avatars (public), im-temp (download)';
      exit 0;
      "
    networks:
      - imzero_net

networks:
  imzero_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16