// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type SendSmsCodeReq struct {
	Mobile string `json:"mobile", validate:"required,mobile"`
	Scene  int32  `json:"scene", validate:"required,gte=1,lte=3"`
}

type SendSmsCodeResp struct {
	CodeKey string `json:"codeKey"`
}
