// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imConversationFieldNames          = builder.RawFieldNames(&ImConversation{})
	imConversationRows                = strings.Join(imConversationFieldNames, ",")
	imConversationRowsExpectAutoSet   = strings.Join(stringx.Remove(imConversationFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imConversationRowsWithPlaceHolder = strings.Join(stringx.Remove(imConversationFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImConversationIdPrefix             = "cache:imMessage:imConversation:id:"
	cacheImMessageImConversationConversationIdPrefix = "cache:imMessage:imConversation:conversationId:"
	cacheImMessageImConversationUserIdFriendIdPrefix = "cache:imMessage:imConversation:userId:friendId:"
)

type (
	imConversationModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImConversation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImConversation, error)
		FindOneByConversationId(ctx context.Context, conversationId string) (*ImConversation, error)
		FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*ImConversation, error)
		Update(ctx context.Context, session sqlx.Session, data *ImConversation) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImConversation) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImConversation) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImConversation, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImConversation, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImConversation, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImConversation, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImConversation, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImConversationModel struct {
		sqlc.CachedConn
		table string
	}

	ImConversation struct {
		Id                 int64          `db:"id"`                   // 会话ID
		ConversationId     string         `db:"conversation_id"`      // 会话唯一标识
		UserId             int64          `db:"user_id"`              // 用户ID
		FriendId           int64          `db:"friend_id"`            // 对方用户ID
		ConversationType   int64          `db:"conversation_type"`    // 会话类型：1-单聊，2-群聊
		LastMessageId      sql.NullInt64  `db:"last_message_id"`      // 最后一条消息ID
		LastMessageContent sql.NullString `db:"last_message_content"` // 最后一条消息内容
		LastMessageTime    sql.NullTime   `db:"last_message_time"`    // 最后一条消息时间
		UnreadCount        int64          `db:"unread_count"`         // 未读消息数
		IsTop              int64          `db:"is_top"`               // 是否置顶：0-否，1-是
		IsMute             int64          `db:"is_mute"`              // 是否免打扰：0-否，1-是
		DelState           int64          `db:"del_state"`            // 删除状态：0-未删除，1-已删除
		DeleteTime         sql.NullTime   `db:"delete_time"`          // 删除时间
		CreateTime         time.Time      `db:"create_time"`          // 创建时间
		UpdateTime         time.Time      `db:"update_time"`          // 更新时间
		Version            int64          `db:"version"`              // 版本号
	}
)

func newImConversationModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImConversationModel {
	return &defaultImConversationModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_conversation`",
	}
}

func (m *defaultImConversationModel) Insert(ctx context.Context, session sqlx.Session, data *ImConversation) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImConversationConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationConversationIdPrefix, data.ConversationId)
	imMessageImConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, data.Id)
	imMessageImConversationUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImConversationUserIdFriendIdPrefix, data.UserId, data.FriendId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imConversationRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ConversationId, data.UserId, data.FriendId, data.ConversationType, data.LastMessageId, data.LastMessageContent, data.LastMessageTime, data.UnreadCount, data.IsTop, data.IsMute, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.ConversationId, data.UserId, data.FriendId, data.ConversationType, data.LastMessageId, data.LastMessageContent, data.LastMessageTime, data.UnreadCount, data.IsTop, data.IsMute, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImConversationConversationIdKey, imMessageImConversationIdKey, imMessageImConversationUserIdFriendIdKey)
}

func (m *defaultImConversationModel) FindOne(ctx context.Context, id int64) (*ImConversation, error) {
	imMessageImConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, id)
	var resp ImConversation
	err := m.QueryRowCtx(ctx, &resp, imMessageImConversationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imConversationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) FindOneByConversationId(ctx context.Context, conversationId string) (*ImConversation, error) {
	imMessageImConversationConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationConversationIdPrefix, conversationId)
	var resp ImConversation
	err := m.QueryRowIndexCtx(ctx, &resp, imMessageImConversationConversationIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `conversation_id` = ? and del_state = ? limit 1", imConversationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, conversationId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*ImConversation, error) {
	imMessageImConversationUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImConversationUserIdFriendIdPrefix, userId, friendId)
	var resp ImConversation
	err := m.QueryRowIndexCtx(ctx, &resp, imMessageImConversationUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? and del_state = ? limit 1", imConversationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) Update(ctx context.Context, session sqlx.Session, newData *ImConversation) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	imMessageImConversationConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationConversationIdPrefix, data.ConversationId)
	imMessageImConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, data.Id)
	imMessageImConversationUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImConversationUserIdFriendIdPrefix, data.UserId, data.FriendId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imConversationRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.ConversationId, newData.UserId, newData.FriendId, newData.ConversationType, newData.LastMessageId, newData.LastMessageContent, newData.LastMessageTime, newData.UnreadCount, newData.IsTop, newData.IsMute, newData.DelState, newData.DeleteTime, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.ConversationId, newData.UserId, newData.FriendId, newData.ConversationType, newData.LastMessageId, newData.LastMessageContent, newData.LastMessageTime, newData.UnreadCount, newData.IsTop, newData.IsMute, newData.DelState, newData.DeleteTime, newData.Version, newData.Id)
	}, imMessageImConversationConversationIdKey, imMessageImConversationIdKey, imMessageImConversationUserIdFriendIdKey)
}

func (m *defaultImConversationModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *ImConversation) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	imMessageImConversationConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationConversationIdPrefix, data.ConversationId)
	imMessageImConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, data.Id)
	imMessageImConversationUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImConversationUserIdFriendIdPrefix, data.UserId, data.FriendId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imConversationRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.ConversationId, newData.UserId, newData.FriendId, newData.ConversationType, newData.LastMessageId, newData.LastMessageContent, newData.LastMessageTime, newData.UnreadCount, newData.IsTop, newData.IsMute, newData.DelState, newData.DeleteTime, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.ConversationId, newData.UserId, newData.FriendId, newData.ConversationType, newData.LastMessageId, newData.LastMessageContent, newData.LastMessageTime, newData.UnreadCount, newData.IsTop, newData.IsMute, newData.DelState, newData.DeleteTime, newData.Version, newData.Id, oldVersion)
	}, imMessageImConversationConversationIdKey, imMessageImConversationIdKey, imMessageImConversationUserIdFriendIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImConversationModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImConversation) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImConversationModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImConversationModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImConversationModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImConversationModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImConversation, error) {

	builder = builder.Columns(imConversationRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImConversation
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImConversation, error) {

	builder = builder.Columns(imConversationRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImConversation
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImConversation, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imConversationRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImConversation
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImConversationModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImConversation, error) {

	builder = builder.Columns(imConversationRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImConversation
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImConversation, error) {

	builder = builder.Columns(imConversationRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImConversation
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImConversationModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImConversationModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImConversationModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imMessageImConversationConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationConversationIdPrefix, data.ConversationId)
	imMessageImConversationIdKey := fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, id)
	imMessageImConversationUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImConversationUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImConversationConversationIdKey, imMessageImConversationIdKey, imMessageImConversationUserIdFriendIdKey)
	return err
}
func (m *defaultImConversationModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImConversationIdPrefix, primary)
}
func (m *defaultImConversationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imConversationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImConversationModel) tableName() string {
	return m.table
}
