// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imMessageFieldNames          = builder.RawFieldNames(&ImMessage{})
	imMessageRows                = strings.Join(imMessageFieldNames, ",")
	imMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(imMessageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(imMessageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImMessageIdPrefix = "cache:imMessage:imMessage:id:"
)

type (
	imMessageModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImMessage, error)
		Update(ctx context.Context, session sqlx.Session, data *ImMessage) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImMessage) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImMessage) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImMessage, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImMessage, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImMessage, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImMessage, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImMessage, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImMessageModel struct {
		sqlc.CachedConn
		table string
	}

	ImMessage struct {
		Id             int64          `db:"id"`              // 消息ID
		FromUserId     int64          `db:"from_user_id"`    // 发送者ID
		ToUserId       int64          `db:"to_user_id"`      // 接收者ID
		ConversationId string         `db:"conversation_id"` // 会话ID
		MessageType    int64          `db:"message_type"`    // 消息类型：1-文本，2-图片，3-语音，4-视频，5-文件
		Content        string         `db:"content"`         // 消息内容
		Extra          sql.NullString `db:"extra"`           // 额外信息(JSON格式)
		Status         int64          `db:"status"`          // 消息状态：0-发送中，1-已发送，2-已送达，3-已读，4-撤回，5-删除
		Seq            int64          `db:"seq"`             // 消息序号，用于排序
		DelState       int64          `db:"del_state"`       // 删除状态：0-未删除，1-已删除
		DeleteTime     sql.NullTime   `db:"delete_time"`     // 删除时间
		CreateTime     time.Time      `db:"create_time"`     // 创建时间
		UpdateTime     time.Time      `db:"update_time"`     // 更新时间
		Version        int64          `db:"version"`         // 版本号
	}
)

func newImMessageModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImMessageModel {
	return &defaultImMessageModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_message`",
	}
}

func (m *defaultImMessageModel) Insert(ctx context.Context, session sqlx.Session, data *ImMessage) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imMessageRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImMessageIdKey)
}

func (m *defaultImMessageModel) FindOne(ctx context.Context, id int64) (*ImMessage, error) {
	imMessageImMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, id)
	var resp ImMessage
	err := m.QueryRowCtx(ctx, &resp, imMessageImMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imMessageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) Update(ctx context.Context, session sqlx.Session, data *ImMessage) (sql.Result, error) {
	imMessageImMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, imMessageImMessageIdKey)
}

func (m *defaultImMessageModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImMessage) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	imMessageImMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.ConversationId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, imMessageImMessageIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImMessageModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImMessage) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImMessageModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImMessageModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImMessageModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImMessageModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImMessage, error) {

	builder = builder.Columns(imMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImMessage, error) {

	builder = builder.Columns(imMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImMessage, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImMessageModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImMessage, error) {

	builder = builder.Columns(imMessageRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImMessage, error) {

	builder = builder.Columns(imMessageRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImMessageModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImMessageModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImMessageModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	imMessageImMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImMessageIdKey)
	return err
}
func (m *defaultImMessageModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImMessageIdPrefix, primary)
}
func (m *defaultImMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imMessageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImMessageModel) tableName() string {
	return m.table
}
