// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imGroupMessageFieldNames          = builder.RawFieldNames(&ImGroupMessage{})
	imGroupMessageRows                = strings.Join(imGroupMessageFieldNames, ",")
	imGroupMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupMessageFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imGroupMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupMessageFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImGroupMessageIdPrefix = "cache:imMessage:imGroupMessage:id:"
)

type (
	imGroupMessageModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImGroupMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImGroupMessage, error)
		Update(ctx context.Context, session sqlx.Session, data *ImGroupMessage) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroupMessage) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroupMessage) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImGroupMessage, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupMessage, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupMessage, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroupMessage, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroupMessage, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImGroupMessageModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroupMessage struct {
		Id          int64          `db:"id"`           // 消息ID
		GroupId     int64          `db:"group_id"`     // 群组ID
		FromUserId  int64          `db:"from_user_id"` // 发送者ID
		MessageType int64          `db:"message_type"` // 消息类型：1-文本，2-图片，3-语音，4-视频，5-文件
		Content     string         `db:"content"`      // 消息内容
		Extra       sql.NullString `db:"extra"`        // 额外信息(JSON格式)
		Status      int64          `db:"status"`       // 消息状态：0-发送中，1-已发送，2-已送达，3-已读，4-撤回，5-删除
		Seq         int64          `db:"seq"`          // 消息序号，用于排序
		DelState    int64          `db:"del_state"`    // 删除状态：0-未删除，1-已删除
		DeleteTime  sql.NullTime   `db:"delete_time"`  // 删除时间
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
		UpdateTime  time.Time      `db:"update_time"`  // 更新时间
		Version     int64          `db:"version"`      // 版本号
	}
)

func newImGroupMessageModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImGroupMessageModel {
	return &defaultImGroupMessageModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_group_message`",
	}
}

func (m *defaultImGroupMessageModel) Insert(ctx context.Context, session sqlx.Session, data *ImGroupMessage) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImGroupMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imGroupMessageRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImGroupMessageIdKey)
}

func (m *defaultImGroupMessageModel) FindOne(ctx context.Context, id int64) (*ImGroupMessage, error) {
	imMessageImGroupMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, id)
	var resp ImGroupMessage
	err := m.QueryRowCtx(ctx, &resp, imMessageImGroupMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupMessageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupMessageModel) Update(ctx context.Context, session sqlx.Session, data *ImGroupMessage) (sql.Result, error) {
	imMessageImGroupMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, imMessageImGroupMessageIdKey)
}

func (m *defaultImGroupMessageModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroupMessage) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	imMessageImGroupMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imGroupMessageRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.FromUserId, data.MessageType, data.Content, data.Extra, data.Status, data.Seq, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, imMessageImGroupMessageIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImGroupMessageModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroupMessage) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImGroupMessageModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImGroupMessageModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupMessageModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupMessageModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImGroupMessage, error) {

	builder = builder.Columns(imGroupMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupMessageModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupMessage, error) {

	builder = builder.Columns(imGroupMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupMessageModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupMessage, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imGroupMessageRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImGroupMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImGroupMessageModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroupMessage, error) {

	builder = builder.Columns(imGroupMessageRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupMessageModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroupMessage, error) {

	builder = builder.Columns(imGroupMessageRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupMessage
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupMessageModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImGroupMessageModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImGroupMessageModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	imMessageImGroupMessageIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImGroupMessageIdKey)
	return err
}
func (m *defaultImGroupMessageModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImGroupMessageIdPrefix, primary)
}
func (m *defaultImGroupMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupMessageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImGroupMessageModel) tableName() string {
	return m.table
}
