// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imGroupFieldNames          = builder.RawFieldNames(&ImGroup{})
	imGroupRows                = strings.Join(imGroupFieldNames, ",")
	imGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImGroupIdPrefix = "cache:imMessage:imGroup:id:"
)

type (
	imGroupModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImGroup, error)
		Update(ctx context.Context, session sqlx.Session, data *ImGroup) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroup) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroup) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImGroup, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroup, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroup, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroup, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroup, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImGroupModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroup struct {
		Id                int64          `db:"id"`                  // 群组ID
		Name              string         `db:"name"`                // 群名称
		Avatar            sql.NullString `db:"avatar"`              // 群头像URL
		Description       sql.NullString `db:"description"`         // 群描述
		Notice            sql.NullString `db:"notice"`              // 群公告
		OwnerId           int64          `db:"owner_id"`            // 群主ID
		MemberCount       int64          `db:"member_count"`        // 当前成员数量
		MaxMembers        int64          `db:"max_members"`         // 最大成员数量
		Status            int64          `db:"status"`              // 群状态：0-禁用，1-正常，2-解散
		IsPrivate         int64          `db:"is_private"`          // 是否私有群：0-公开，1-私有
		JoinApproval      int64          `db:"join_approval"`       // 入群是否需要审批：0-不需要，1-需要
		AllowInvite       int64          `db:"allow_invite"`        // 是否允许邀请：0-不允许，1-允许
		AllowMemberModify int64          `db:"allow_member_modify"` // 是否允许成员修改群信息：0-不允许，1-允许
		DelState          int64          `db:"del_state"`           // 删除状态：0-未删除，1-已删除
		DeleteTime        sql.NullTime   `db:"delete_time"`         // 删除时间
		CreateTime        time.Time      `db:"create_time"`         // 创建时间
		UpdateTime        time.Time      `db:"update_time"`         // 更新时间
		Version           int64          `db:"version"`             // 版本号
	}
)

func newImGroupModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImGroupModel {
	return &defaultImGroupModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_group`",
	}
}

func (m *defaultImGroupModel) Insert(ctx context.Context, session sqlx.Session, data *ImGroup) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImGroupIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imGroupRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImGroupIdKey)
}

func (m *defaultImGroupModel) FindOne(ctx context.Context, id int64) (*ImGroup, error) {
	imMessageImGroupIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, id)
	var resp ImGroup
	err := m.QueryRowCtx(ctx, &resp, imMessageImGroupIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) Update(ctx context.Context, session sqlx.Session, data *ImGroup) (sql.Result, error) {
	imMessageImGroupIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, imMessageImGroupIdKey)
}

func (m *defaultImGroupModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroup) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	imMessageImGroupIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imGroupRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.Name, data.Avatar, data.Description, data.Notice, data.OwnerId, data.MemberCount, data.MaxMembers, data.Status, data.IsPrivate, data.JoinApproval, data.AllowInvite, data.AllowMemberModify, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, imMessageImGroupIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImGroupModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroup) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImGroupModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImGroupModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImGroup, error) {

	builder = builder.Columns(imGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroup, error) {

	builder = builder.Columns(imGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroup, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imGroupRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImGroupModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroup, error) {

	builder = builder.Columns(imGroupRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroup, error) {

	builder = builder.Columns(imGroupRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroup
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImGroupModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImGroupModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	imMessageImGroupIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImGroupIdKey)
	return err
}
func (m *defaultImGroupModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImGroupIdPrefix, primary)
}
func (m *defaultImGroupModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImGroupModel) tableName() string {
	return m.table
}
