// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imGroupRequestFieldNames          = builder.RawFieldNames(&ImGroupRequest{})
	imGroupRequestRows                = strings.Join(imGroupRequestFieldNames, ",")
	imGroupRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(imGroupRequestFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imGroupRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(imGroupRequestFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImGroupRequestIdPrefix = "cache:imMessage:imGroupRequest:id:"
)

type (
	imGroupRequestModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImGroupRequest) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImGroupRequest, error)
		Update(ctx context.Context, session sqlx.Session, data *ImGroupRequest) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroupRequest) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroupRequest) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImGroupRequest, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupRequest, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupRequest, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroupRequest, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroupRequest, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImGroupRequestModel struct {
		sqlc.CachedConn
		table string
	}

	ImGroupRequest struct {
		Id            int64          `db:"id"`             // ID
		GroupId       int64          `db:"group_id"`       // 群组ID
		UserId        int64          `db:"user_id"`        // 申请人ID
		InviterId     sql.NullInt64  `db:"inviter_id"`     // 邀请人ID(如果是邀请入群)
		RequestType   int64          `db:"request_type"`   // 请求类型：1-申请入群，2-邀请入群
		Message       sql.NullString `db:"message"`        // 申请消息
		Status        int64          `db:"status"`         // 申请状态：0-待处理，1-已同意，2-已拒绝，3-已过期
		HandleUserId  sql.NullInt64  `db:"handle_user_id"` // 处理人ID
		HandleMessage sql.NullString `db:"handle_message"` // 处理消息
		HandleTime    sql.NullTime   `db:"handle_time"`    // 处理时间
		ExpireTime    sql.NullTime   `db:"expire_time"`    // 过期时间
		DelState      int64          `db:"del_state"`      // 删除状态：0-未删除，1-已删除
		DeleteTime    sql.NullTime   `db:"delete_time"`    // 删除时间
		CreateTime    time.Time      `db:"create_time"`    // 创建时间
		UpdateTime    time.Time      `db:"update_time"`    // 更新时间
		Version       int64          `db:"version"`        // 版本号
	}
)

func newImGroupRequestModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImGroupRequestModel {
	return &defaultImGroupRequestModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_group_request`",
	}
}

func (m *defaultImGroupRequestModel) Insert(ctx context.Context, session sqlx.Session, data *ImGroupRequest) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImGroupRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imGroupRequestRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImGroupRequestIdKey)
}

func (m *defaultImGroupRequestModel) FindOne(ctx context.Context, id int64) (*ImGroupRequest, error) {
	imMessageImGroupRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, id)
	var resp ImGroupRequest
	err := m.QueryRowCtx(ctx, &resp, imMessageImGroupRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImGroupRequestModel) Update(ctx context.Context, session sqlx.Session, data *ImGroupRequest) (sql.Result, error) {
	imMessageImGroupRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imGroupRequestRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, imMessageImGroupRequestIdKey)
}

func (m *defaultImGroupRequestModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImGroupRequest) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	imMessageImGroupRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imGroupRequestRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.InviterId, data.RequestType, data.Message, data.Status, data.HandleUserId, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, imMessageImGroupRequestIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImGroupRequestModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImGroupRequest) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImGroupRequestModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImGroupRequestModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupRequestModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImGroupRequestModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImGroupRequest, error) {

	builder = builder.Columns(imGroupRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupRequestModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupRequest, error) {

	builder = builder.Columns(imGroupRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupRequestModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImGroupRequest, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imGroupRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImGroupRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImGroupRequestModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImGroupRequest, error) {

	builder = builder.Columns(imGroupRequestRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupRequestModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImGroupRequest, error) {

	builder = builder.Columns(imGroupRequestRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImGroupRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImGroupRequestModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImGroupRequestModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImGroupRequestModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	imMessageImGroupRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImGroupRequestIdKey)
	return err
}
func (m *defaultImGroupRequestModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImGroupRequestIdPrefix, primary)
}
func (m *defaultImGroupRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imGroupRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImGroupRequestModel) tableName() string {
	return m.table
}
