// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GroupInfo struct {
	Id                int64  `json:"id"`
	Name              string `json:"name"`
	Avatar            string `json:"avatar"`
	Description       string `json:"description"`
	Notice            string `json:"notice"` // 群公告
	OwnerId           int64  `json:"ownerId"`
	MemberCount       int32  `json:"memberCount"`
	MaxMembers        int32  `json:"maxMembers"`        // 最大成员数
	Status            int32  `json:"status"`            // 0:正常 1:禁用
	IsPrivate         bool   `json:"isPrivate"`         // 是否私有群
	JoinApproval      bool   `json:"joinApproval"`      // 是否需要审批
	AllowInvite       bool   `json:"allowInvite"`       // 是否允许成员邀请
	AllowMemberModify bool   `json:"allowMemberModify"` // 是否允许成员修改群信息
	CreateTime        int64  `json:"createTime"`
	UpdateTime        int64  `json:"updateTime"`
}

type GroupMember struct {
	UserId      int64  `json:"userId"`
	GroupId     int64  `json:"groupId"`
	Nickname    string `json:"nickname"` // 群昵称
	Avatar      string `json:"avatar"`
	Role        int32  `json:"role"`        // 1:群主 2:管理员 3:普通成员
	Status      int32  `json:"status"`      // 0:正常 1:禁言
	MuteEndTime int64  `json:"muteEndTime"` // 禁言结束时间
	JoinTime    int64  `json:"joinTime"`
}

type GroupMessage struct {
	Id          int64  `json:"id"`
	GroupId     int64  `json:"groupId"`
	FromUserId  int64  `json:"fromUserId"`
	MessageType int32  `json:"messageType"`
	Content     string `json:"content"`
	Extra       string `json:"extra"`
	Status      int32  `json:"status"`
	CreateTime  int64  `json:"createTime"`
}
