// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imFriendRequestFieldNames          = builder.RawFieldNames(&ImFriendRequest{})
	imFriendRequestRows                = strings.Join(imFriendRequestFieldNames, ",")
	imFriendRequestRowsExpectAutoSet   = strings.Join(stringx.Remove(imFriendRequestFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imFriendRequestRowsWithPlaceHolder = strings.Join(stringx.Remove(imFriendRequestFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImFriendRequestIdPrefix = "cache:imMessage:imFriendRequest:id:"
)

type (
	imFriendRequestModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImFriendRequest) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImFriendRequest, error)
		Update(ctx context.Context, session sqlx.Session, data *ImFriendRequest) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImFriendRequest) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImFriendRequest) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImFriendRequest, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImFriendRequest, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImFriendRequest, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImFriendRequest, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImFriendRequest, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImFriendRequestModel struct {
		sqlc.CachedConn
		table string
	}

	ImFriendRequest struct {
		Id            int64          `db:"id"`             // ID
		FromUserId    int64          `db:"from_user_id"`   // 发起者ID
		ToUserId      int64          `db:"to_user_id"`     // 接收者ID
		Message       sql.NullString `db:"message"`        // 请求验证消息
		Status        int64          `db:"status"`         // 请求状态：0-待处理，1-已同意，2-已拒绝，3-已过期
		HandleMessage sql.NullString `db:"handle_message"` // 处理消息
		HandleTime    sql.NullTime   `db:"handle_time"`    // 处理时间
		ExpireTime    sql.NullTime   `db:"expire_time"`    // 过期时间
		DelState      int64          `db:"del_state"`      // 删除状态：0-未删除，1-已删除
		DeleteTime    sql.NullTime   `db:"delete_time"`    // 删除时间
		CreateTime    time.Time      `db:"create_time"`    // 创建时间
		UpdateTime    time.Time      `db:"update_time"`    // 更新时间
		Version       int64          `db:"version"`        // 版本号
	}
)

func newImFriendRequestModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImFriendRequestModel {
	return &defaultImFriendRequestModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_friend_request`",
	}
}

func (m *defaultImFriendRequestModel) Insert(ctx context.Context, session sqlx.Session, data *ImFriendRequest) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, imFriendRequestRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImFriendRequestIdKey)
}

func (m *defaultImFriendRequestModel) FindOne(ctx context.Context, id int64) (*ImFriendRequest, error) {
	imMessageImFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, id)
	var resp ImFriendRequest
	err := m.QueryRowCtx(ctx, &resp, imMessageImFriendRequestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imFriendRequestRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) Update(ctx context.Context, session sqlx.Session, data *ImFriendRequest) (sql.Result, error) {
	imMessageImFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imFriendRequestRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id)
	}, imMessageImFriendRequestIdKey)
}

func (m *defaultImFriendRequestModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImFriendRequest) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	imMessageImFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imFriendRequestRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.FromUserId, data.ToUserId, data.Message, data.Status, data.HandleMessage, data.HandleTime, data.ExpireTime, data.DelState, data.DeleteTime, data.Version, data.Id, oldVersion)
	}, imMessageImFriendRequestIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImFriendRequestModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImFriendRequest) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImFriendRequestModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImFriendRequestModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImFriendRequestModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImFriendRequestModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImFriendRequest, error) {

	builder = builder.Columns(imFriendRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImFriendRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImFriendRequest, error) {

	builder = builder.Columns(imFriendRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImFriendRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImFriendRequest, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imFriendRequestRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImFriendRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImFriendRequestModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImFriendRequest, error) {

	builder = builder.Columns(imFriendRequestRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImFriendRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImFriendRequest, error) {

	builder = builder.Columns(imFriendRequestRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImFriendRequest
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImFriendRequestModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImFriendRequestModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImFriendRequestModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	imMessageImFriendRequestIdKey := fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImFriendRequestIdKey)
	return err
}
func (m *defaultImFriendRequestModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImFriendRequestIdPrefix, primary)
}
func (m *defaultImFriendRequestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imFriendRequestRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImFriendRequestModel) tableName() string {
	return m.table
}
