// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"im-zero/pkg/globalkey"
)

var (
	imUserBlacklistFieldNames          = builder.RawFieldNames(&ImUserBlacklist{})
	imUserBlacklistRows                = strings.Join(imUserBlacklistFieldNames, ",")
	imUserBlacklistRowsExpectAutoSet   = strings.Join(stringx.Remove(imUserBlacklistFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	imUserBlacklistRowsWithPlaceHolder = strings.Join(stringx.Remove(imUserBlacklistFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheImMessageImUserBlacklistIdPrefix                  = "cache:imMessage:imUserBlacklist:id:"
	cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix = "cache:imMessage:imUserBlacklist:userId:blockedUserId:"
)

type (
	imUserBlacklistModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ImUserBlacklist, error)
		FindOneByUserIdBlockedUserId(ctx context.Context, userId int64, blockedUserId int64) (*ImUserBlacklist, error)
		Update(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ImUserBlacklist, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImUserBlacklist, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImUserBlacklist, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImUserBlacklist, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImUserBlacklist, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultImUserBlacklistModel struct {
		sqlc.CachedConn
		table string
	}

	ImUserBlacklist struct {
		Id            int64          `db:"id"`              // ID
		UserId        int64          `db:"user_id"`         // 用户ID
		BlockedUserId int64          `db:"blocked_user_id"` // 被拉黑用户ID
		Reason        sql.NullString `db:"reason"`          // 拉黑原因
		DelState      int64          `db:"del_state"`       // 删除状态：0-未删除，1-已删除
		DeleteTime    sql.NullTime   `db:"delete_time"`     // 删除时间
		CreateTime    time.Time      `db:"create_time"`     // 创建时间
		UpdateTime    time.Time      `db:"update_time"`     // 更新时间
		Version       int64          `db:"version"`         // 版本号
	}
)

func newImUserBlacklistModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultImUserBlacklistModel {
	return &defaultImUserBlacklistModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`im_user_blacklist`",
	}
}

func (m *defaultImUserBlacklistModel) Insert(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) (sql.Result, error) {
	data.DeleteTime = sql.NullTime{Time: time.Unix(0, 0), Valid: false}
	data.DelState = globalkey.DelStateNo
	imMessageImUserBlacklistIdKey := fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, data.Id)
	imMessageImUserBlacklistUserIdBlockedUserIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix, data.UserId, data.BlockedUserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, imUserBlacklistRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.BlockedUserId, data.Reason, data.DelState, data.DeleteTime, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.BlockedUserId, data.Reason, data.DelState, data.DeleteTime, data.Version)
	}, imMessageImUserBlacklistIdKey, imMessageImUserBlacklistUserIdBlockedUserIdKey)
}

func (m *defaultImUserBlacklistModel) FindOne(ctx context.Context, id int64) (*ImUserBlacklist, error) {
	imMessageImUserBlacklistIdKey := fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, id)
	var resp ImUserBlacklist
	err := m.QueryRowCtx(ctx, &resp, imMessageImUserBlacklistIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imUserBlacklistRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) FindOneByUserIdBlockedUserId(ctx context.Context, userId int64, blockedUserId int64) (*ImUserBlacklist, error) {
	imMessageImUserBlacklistUserIdBlockedUserIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix, userId, blockedUserId)
	var resp ImUserBlacklist
	err := m.QueryRowIndexCtx(ctx, &resp, imMessageImUserBlacklistUserIdBlockedUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `blocked_user_id` = ? and del_state = ? limit 1", imUserBlacklistRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, blockedUserId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) Update(ctx context.Context, session sqlx.Session, newData *ImUserBlacklist) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	imMessageImUserBlacklistIdKey := fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, data.Id)
	imMessageImUserBlacklistUserIdBlockedUserIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix, data.UserId, data.BlockedUserId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, imUserBlacklistRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.BlockedUserId, newData.Reason, newData.DelState, newData.DeleteTime, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.BlockedUserId, newData.Reason, newData.DelState, newData.DeleteTime, newData.Version, newData.Id)
	}, imMessageImUserBlacklistIdKey, imMessageImUserBlacklistUserIdBlockedUserIdKey)
}

func (m *defaultImUserBlacklistModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *ImUserBlacklist) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	imMessageImUserBlacklistIdKey := fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, data.Id)
	imMessageImUserBlacklistUserIdBlockedUserIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix, data.UserId, data.BlockedUserId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, imUserBlacklistRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.BlockedUserId, newData.Reason, newData.DelState, newData.DeleteTime, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.BlockedUserId, newData.Reason, newData.DelState, newData.DeleteTime, newData.Version, newData.Id, oldVersion)
	}, imMessageImUserBlacklistIdKey, imMessageImUserBlacklistUserIdBlockedUserIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultImUserBlacklistModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ImUserBlacklist) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = sql.NullTime{Time: time.Now(), Valid: true}
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ImUserBlacklistModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultImUserBlacklistModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImUserBlacklistModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultImUserBlacklistModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ImUserBlacklist, error) {

	builder = builder.Columns(imUserBlacklistRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImUserBlacklist
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImUserBlacklist, error) {

	builder = builder.Columns(imUserBlacklistRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImUserBlacklist
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ImUserBlacklist, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(imUserBlacklistRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ImUserBlacklist
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultImUserBlacklistModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ImUserBlacklist, error) {

	builder = builder.Columns(imUserBlacklistRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImUserBlacklist
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ImUserBlacklist, error) {

	builder = builder.Columns(imUserBlacklistRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ImUserBlacklist
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultImUserBlacklistModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultImUserBlacklistModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultImUserBlacklistModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	imMessageImUserBlacklistIdKey := fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, id)
	imMessageImUserBlacklistUserIdBlockedUserIdKey := fmt.Sprintf("%s%v:%v", cacheImMessageImUserBlacklistUserIdBlockedUserIdPrefix, data.UserId, data.BlockedUserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, imMessageImUserBlacklistIdKey, imMessageImUserBlacklistUserIdBlockedUserIdKey)
	return err
}
func (m *defaultImUserBlacklistModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheImMessageImUserBlacklistIdPrefix, primary)
}
func (m *defaultImUserBlacklistModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", imUserBlacklistRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultImUserBlacklistModel) tableName() string {
	return m.table
}
