// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: verifycode.proto

package server

import (
	"context"

	"im-zero/app/verifycode/cmd/rpc/internal/logic"
	"im-zero/app/verifycode/cmd/rpc/internal/svc"
	"im-zero/app/verifycode/cmd/rpc/pb"
)

type VerifycodeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVerifycodeServer
}

func NewVerifycodeServer(svcCtx *svc.ServiceContext) *VerifycodeServer {
	return &VerifycodeServer{
		svcCtx: svcCtx,
	}
}

// 发送验证码
func (s *VerifycodeServer) SendSmsCode(ctx context.Context, in *pb.SendSmsCodeReq) (*pb.SendSmsCodeResp, error) {
	l := logic.NewSendSmsCodeLogic(ctx, s.svcCtx)
	return l.SendSmsCode(in)
}

// 验证验证码
func (s *VerifycodeServer) VerifySmsCode(ctx context.Context, in *pb.VerifySmsCodeReq) (*pb.VerifySmsCodeResp, error) {
	l := logic.NewVerifySmsCodeLogic(ctx, s.svcCtx)
	return l.VerifySmsCode(in)
}
