// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FriendInfo struct {
	Id         int64    `json:"id"`
	UserId     int64    `json:"userId"`
	FriendId   int64    `json:"friendId"`
	UserInfo   UserInfo `json:"userInfo"`
	Remark     string   `json:"remark"`     // 备注名
	GroupId    int64    `json:"groupId"`    // 好友分组ID
	Status     int32    `json:"status"`     // 状态：0-待验证，1-正常，2-删除
	CreateTime int64    `json:"createTime"`
}

type FriendRequest struct {
	Id         int64    `json:"id"`
	FromUser   UserInfo `json:"fromUser"`
	ToUser     UserInfo `json:"toUser"`
	Message    string   `json:"message"` // 验证消息
	Status     int32    `json:"status"`  // 0:待处理 1:已同意 2:已拒绝 3:已过期
	CreateTime int64    `json:"createTime"`
	HandleTime int64    `json:"handleTime,optional"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Sign     string `json:"sign"`
	Status   int32  `json:"status"` // 0:离线 1:在线 2:忙碌 3:勿扰
}
