// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Conversation struct {
	Id          string  `json:"id"`
	Type        int32   `json:"type"` // 1:单聊 2:群聊
	Name        string  `json:"name,optional"`
	Avatar      string  `json:"avatar,optional"`
	LastMessage Message `json:"lastMessage"`
	UnreadCount int32   `json:"unreadCount"`
	UpdateTime  int64   `json:"updateTime"`
}

type Message struct {
	Id             int64  `json:"id"`
	FromUserId     int64  `json:"fromUserId"`
	ToUserId       int64  `json:"toUserId"`
	ConversationId string `json:"conversationId"`
	MessageType    int32  `json:"messageType"` // 1:文本 2:图片 3:语音 4:视频 5:文件
	Content        string `json:"content"`
	Extra          string `json:"extra,optional"` // 扩展信息(JSON格式)
	Status         int32  `json:"status"`         // 0:发送中 1:已发送 2:已送达 3:已读 4:撤回 5:删除
	CreateTime     int64  `json:"createTime"`
	UpdateTime     int64  `json:"updateTime"`
}
